### ISSUE TITLE
Logo bjtu-travel-agency

### ISSUE THREAD

**Issue by familqasimov** [victorpugin/bjtu-travel-agency#3]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![1024](https://user-images.githubusercontent.com/36432269/39398737-2609393a-4b23-11e8-853f-49354ead0b2c.png)

**Comment by victorpugin** [comment]
Hi sir. Thank you for your concern about my work. You did a great job, but this project will stop soon. This is a scholar assignment and, unfortunately, is not design for real use case. However, if you still want to send me a PR, I will take a look.
